# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='housecf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='housecf5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='houseinfo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rentfl',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tier',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
