# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0002_auto_20170519_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, null=True)),
                ('streetname', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('blockid', models.CharField(max_length=30, null=True)),
                ('blockname', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
